server:
  port: 9001
spring:
  application:
    name: consumer
  #分布式链路追踪，服务会向zipkin的base-url发送服务运行信息
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #采样比例，10即10%，100即所有请求都采样
      rate: 100
      
#为feign开启断路器功能
feign:
  hystrix:
    enabled: true