server:
  port: 3001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #静态路由方式
        - id: dept
          uri: http://localhost:8001
          predicates:
            - Path=/**
      discovery:
        locator:
          #开启服务发现路由方式，请求地址格式为：http://ip:port/服务名称/服务资源路径
          #服务名称需要与注册中心的服务名称大小写保持一致
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://registry7001:7001/eureka/
