server:
  port: 8001
  
spring:
  application:
    name: provider-dept
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    #以{cipher}开头，spring cloud config会把面的内容进行解密
    #password: '{cipher}7e2ba34842bade307ef3aa21b383f6c2bd18703cb4e8383ee9090dd773e4a965'
    password: mysqlAdmin
    driver-class-name: com.mysql.jdbc.Driver
  #分布式链路追踪，服务会向zipkin的base-url发送服务运行信息
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #采样比例，10即10%，100即所有请求都采样
      rate: 90
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enabled-by-default: true
    
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #指定mapper.xml文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml  #指定mybatis全局配置文件所在路径
