server:
  port: 2001

spring:
  application:
    name: zuul
zuul:
  host:
    connect-timeout-millis: 2000 #设置连接超时时间
    socket-timeout-millis: 1000 #设置socket超时时间
    max-total-connections: 200 #设置整个网关最大的连接数
    max-per-route-connections: 20 #设置网关每个路由最大连接数
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 100
  routes:
    dept1:
      #url方式配置路由
      path: /dept-api/**
      url: http://localhost:8001
    user:
      #服务实例方式配置路由
      path: /user-api/**
      serviceId: provider-user
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enabled-by-default: true
  endpoint:
    routes:
      enabled: true