server:
  port: 2001

spring:
  application:
    name: zuul
  #分布式链路追踪，服务会向zipkin的base-url发送服务运行信息
  zipkin:
    base-url: http://localhost:9411/
    
zuul:
  host:
    connect-timeout-millis: 2000 #设置连接超时时间
    socket-timeout-millis: 1000 #设置socket超时时间
    max-total-connections: 200 #设置整个网关最大的连接数
    max-per-route-connections: 20 #设置网关每个路由最大连接数
  routes:
    dept:
      #url方式配置路由
      #当访问http://localhost:2001/dept-api/dept/list时，相当于访问http://localhost:2001/dept/list
      path: /dept-api/**
      url: http://localhost:8001
    user:
      #服务实例方式配置路由
      path: /user-api/**
      serviceId: provider-user
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enabled-by-default: true
  endpoint:
    routes:
      #允许查看路由规则，访问地址为：http://localhost:2001/actuator/routes
      enabled: true